### ISSUE TITLE
currentUser problem

### ISSUE THREAD

**Issue by yylhyyw** [chenjunlee/IoT-Simulation-Platform#5]
in UserList.java
I dont know where you reset the currentUser, if currentUser is set to -1, 
it will cause problem when you set the user and delete the user and then reset the project, 
after that import database, it will cause error because currentUser is set to -1, will report out of bound.

tried fix: set currentUser and lastUser to 0, the error still exists

**Comment by bangtran001** [comment]
This error was caused by action of changing combobox user

Fixed
